/*
 * File: app/controller/LoginController.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Cobuy.controller.LoginController', {
    extend: 'Ext.app.Controller',

    onLoginButtonClick: function(button, e, eOpts) {
        /**var win = button.up('window');

        var username = win.down('#username').getValue();

        var password = win.down('#password').getValue();

        //send to the server

        var win = button.up('window'),
        			formPanel = win.down('form');

        			if(formPanel.getForm().isValid()){
        				formPanel.getForm().submit({
        					clientValidation: true,
        					url:'/cobuy/index.php?r=Members/login',

                           //success or failure
        					success: function(form, action) {
        						var result = action.result;
        						if(result.success) {
        							Ext.Msg.alert('Login Status' ,'<strong><font color="green">'+ result.msg +'</font></strong>' + ','+ 'You are logged in');
                                    console.log('membership subscription is active?:',result.subscription_active_status);
                                    //activate the account and cart buttons

                                    if(result.subscription_active_status === true){
                                         Ext.getCmp('mainviewport').down('#cartBtn').setDisabled(false);
                                        var values = {
                                            userid:result.userid
                                        };
                                        Ext.getCmp('mainviewport').down('#userid').getForm().setValues(values);
                                         Ext.getCmp('mainviewport').down('#productsDataview').getStore().load();
                                    }else{
                                        Ext.getCmp('mainviewport').down('#cartBtn').setDisabled(false);

                                    }
                                    Ext.getCmp('mainviewport').down('#accountsBtn').setDisabled(false);
                                    Ext.getCmp('mainviewport').down('#signinBtn').setVisible(false);
                                    Ext.getCmp('mainviewport').down('#logoutBtn').setVisible(true);
                                    Ext.getCmp('mainviewport').down('#joinBtn').setVisible(false);
                                    Ext.getCmp('mainviewport').down('#joinSeparator').setVisible(false);

                                    if(Ext.getCmp('productsdetailwin') != null || Ext.getCmp('productsdetailwin') != undefined){
                                        Ext.getCmp('productsdetailwin').destroy();
                                    }
                                    if(Ext.getCmp('productdetailspanelforproductswithconstituentswin') != null || Ext.getCmp('productdetailspanelforproductswithconstituentswin') != undefined){
                                        Ext.getCmp('productdetailspanelforproductswithconstituentswin').destroy();
                                    }
                                    if(Ext.getCmp('constituentproductdetailswin') != null || Ext.getCmp('constituentproductdetailswin') != undefined){
                                         Ext.getCmp('constituentproductdetailswin').destroy();
                                    }

                              	win.close();
        						} else {
                                    Ext.Msg.alert('Login Status',result.msg);
        						}
        					},
        					failure: function(form, action) {
        						var result = action.result;
                                switch(action.failureType) {
        							case Ext.form.action.Action.CLIENT_INVALID:
        							Ext.Msg.alert('Failure', 'Form fields may not be submitted with invalid values');
        							break;
        							case Ext.form.action.Action.CONNECT_FAILURE:
        							Ext.Msg.alert('Failure', 'Ajax communication failed');
        							break;
        							case Ext.form.action.Action.SERVER_INVALID:
        								Ext.Msg.alert('Login Status', result.msg);
        						}
        					}
        				});
        			}

                    **/

        var win = button.up('window');

        var username = win.down('#username').getValue();

        var password = win.down('#password').getValue();

        var formPanel = win.down('form');


        Ext.Ajax.request({
           url:'/cobuy/index.php?r=Members/login',
           params: formPanel.getForm().getFieldValues(),
                       success: function(response){
        				var jsonResponse = Ext.decode(response.responseText);
                          if(jsonResponse.success){
                               var result = jsonResponse;
                              var msg = jsonResponse.msg;
        					  Ext.Msg.alert('Success!', msg);
                              if(jsonResponse.subscription_active_status === true){
                                         Ext.getCmp('mainviewport').down('#cartBtn').setDisabled(false);
                                        var values = {
                                            userid:jsonResponse.userid
                                        };
                                        Ext.getCmp('mainviewport').down('#userid').getForm().setValues(values);
                                         Ext.getCmp('mainviewport').down('#productsDataview').getStore().load();
                                    }else{
                                        Ext.getCmp('mainviewport').down('#cartBtn').setDisabled(false);

                                    }
                                    Ext.getCmp('mainviewport').down('#accountsBtn').setDisabled(false);
                                    Ext.getCmp('mainviewport').down('#signinBtn').setVisible(false);
                                    Ext.getCmp('mainviewport').down('#logoutBtn').setVisible(true);
                                    Ext.getCmp('mainviewport').down('#joinBtn').setVisible(false);
                                    Ext.getCmp('mainviewport').down('#joinSeparator').setVisible(false);

                                    if(Ext.getCmp('productsdetailwin') != null || Ext.getCmp('productsdetailwin') != undefined){
                                        Ext.getCmp('productsdetailwin').destroy();
                                    }
                                    if(Ext.getCmp('productdetailspanelforproductswithconstituentswin') != null || Ext.getCmp('productdetailspanelforproductswithconstituentswin') != undefined){
                                        Ext.getCmp('productdetailspanelforproductswithconstituentswin').destroy();
                                    }
                                    if(Ext.getCmp('constituentproductdetailswin') != null || Ext.getCmp('constituentproductdetailswin') != undefined){
                                         Ext.getCmp('constituentproductdetailswin').destroy();
                                    }

                            win.close();

                          }else{
        						Ext.Msg.alert('ERROR', jsonResponse.msg);
        				  }
                   },
        		   failure: function(response, options) {
        				Ext.Msg.alert('Faulure Error', response.responseText);
        				}

            });

    },

    onLogOutThisUserButtonClick: function(button, e, eOpts) {
        Ext.Ajax.request({
           url: '/cobuy/index.php?r=Members/logout',
                       success: function(response){
        				var jsonResponse = Ext.decode(response.responseText);
                          if(jsonResponse.success){
                              var msg = jsonResponse.msg;
                              Ext.Msg.alert('Login Status','<font color="purple">'+msg+'</font>');

        					 Ext.getCmp('mainviewport').down('#cartBtn').setDisabled(true);
                             Ext.getCmp('mainviewport').down('#accountsBtn').setDisabled(true);
        					 Ext.getCmp('mainviewport').down('#logoutBtn').setVisible(false);
        					 Ext.getCmp('mainviewport').down('#signinBtn').setVisible(true);
                             Ext.getCmp('mainviewport').down('#joinBtn').setVisible(true);
                             Ext.getCmp('mainviewport').down('#joinSeparator').setVisible(true);

                              var values = {
                                  userid:0
                              };

                              Ext.getCmp('mainviewport').down('#userid').getForm().setValues(values);

                               Ext.getCmp('mainviewport').down('#productsDataview').getStore().load();


                          }

                   }





        });
    },

    init: function(application) {
        this.control({
            "login button#loginBtn": {
                click: this.onLoginButtonClick
            },
            "mainviewport button#logoutBtn": {
                click: this.onLogOutThisUserButtonClick
            }
        });
    }

});
