/*
 * File: app/controller/MainviewportController.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Cobuy.controller.MainviewportController', {
    extend: 'Ext.app.Controller',

    models: [
        'Homepage'
    ],
    stores: [
        'Members',
        'AllProducts',
        'Quotes',
        'Escrows',
        'Futures',
        'Vouchers',
        'Categories',
        'Wallet',
        'ServiceCategories',
        'CategoryProductTypes',
        'SingleMemberDetail',
        'StatesInACountry',
        'CitiesInAState',
        'HomePage'
    ],
    views: [
        'NewMembershipSubscriptionWin',
        'MembershipSubscriptionForm',
        'Mainviewport',
        'ItemsInACartWin'
    ],

    onAboutUsButtonClick: function(button, e, eOpts) {
        var win = Ext.create('Cobuy.view.AboutUsWin');


        var form = win.down('form');


        Ext.Ajax.request({

        				 url: '/cobuy/index.php?r=WebsiteAboutUs/retrieveWebsiteAboutUs',
        			     //success or failure
        				success: function(response){
        				var jsonResponse = Ext.decode(response.responseText);
        					if (jsonResponse.success) {

                                var introduction = jsonResponse.aboutus.introduction;
                                var who_we_are = jsonResponse.aboutus.who_we_are;
                                var who_we_serve = jsonResponse.aboutus.who_we_serve;
                                var our_mission_and_vision = jsonResponse.aboutus.our_mission_and_vision;
                                var status = jsonResponse.aboutus.status;
                                var id = jsonResponse.aboutus.id;




        					}



        					var values = {

                                id:id,
                                introduction:introduction,
                                who_we_are:who_we_are,
                                who_we_serve:who_we_serve,
                                our_mission_and_vision:our_mission_and_vision,
                                status:status



        					};


        					form.getForm().setValues(values);


        				}




        			});

        win.show();
    },

    onServicesButtonClick: function(button, e, eOpts) {
        var win = Ext.create('Cobuy.view.ServicesWin');

        var form = win.down('form');

        Ext.Ajax.request({

        				 url: '/cobuy/index.php?r=WebsiteServices/retrieveWebsiteServicesContent',
        			     //success or failure
        				success: function(response){
        				var jsonResponse = Ext.decode(response.responseText);
        					if (jsonResponse.success) {

                                var introduction = jsonResponse.services.introduction;
                                var service_general = jsonResponse.services.service_general;
                                var service_share = jsonResponse.services.service_share;
                                var service_business = jsonResponse.services.service_business;
                                var status = jsonResponse.services.status;
                                var id = jsonResponse.services.id;




        					}



        					var values = {

                                id:id,
                                introduction:introduction,
                                service_general:service_general,
                                service_share:service_share,
                                service_business:service_business,
                                status:status



        					};


        					form.getForm().setValues(values);


        				}




        			});

        win.show();
    },

    onMembershipButtonClick: function(button, e, eOpts) {
        var win = Ext.create('Cobuy.view.MembershipWin');

        var form = win.down('form');

        Ext.Ajax.request({

        				 url: '/cobuy/index.php?r=WebsiteMembership/retrieveWebsiteMembershipContent',
        			     //success or failure
        				success: function(response){
        				var jsonResponse = Ext.decode(response.responseText);
        					if (jsonResponse.success) {

                                var introduction = jsonResponse.membership.introduction;
                                var membership_basic = jsonResponse.membership.membership_basic;
                                var membership_business = jsonResponse.membership.membership_business;
                                var membership_dons = jsonResponse.membership.membership_dons;
                                var membership_basic_prime = jsonResponse.membership.membership_basic_prime;
                                var membership_business_prime = jsonResponse.membership.membership_business_prime;
                                var status = jsonResponse.membership.status;
                                var id = jsonResponse.membership.id;




        					}



        					var values = {

                                id:id,
                                introduction:introduction,
                                membership_basic:membership_basic,
                                membership_business:membership_business,
                                membership_dons:membership_dons,
                                status:status,
                                membership_basic_prime:membership_basic_prime,
                                membership_business_prime:membership_business_prime




        					};


        					form.getForm().setValues(values);


        				}




        			});

        win.show();
    },

    onContactUsButtonClick: function(button, e, eOpts) {
        var win = Ext.create('Cobuy.view.ContactUsWin');

        win.show();
    },

    onAccountsButtonClick: function(button, e, eOpts) {
        var win = Ext.create('Cobuy.view.MemberAccountDetailWin');

        var form = win.down('form');

        Ext.Ajax.request({

        				 url: '/cobuy/index.php?r=Members/retrieveMemberAccountInformation',
        			     //success or failure
        				success: function(response){
        				var jsonResponse = Ext.decode(response.responseText);
        					if (jsonResponse.success) {

                                var username = jsonResponse.member.username;
                                var email = jsonResponse.member.email;
                                var membership_number = jsonResponse.member.membership_number;
                                var firstname = jsonResponse.member.firstname;
                                var middlename = jsonResponse.member.middlename;
                                var lastname = jsonResponse.member.lastname;
                                var gender = jsonResponse.member.gender;
                                var address1 = jsonResponse.member.address1;
                                var address2 = jsonResponse.member.address2;
                                var dateofbirth = jsonResponse.member.dateofbirth;
                                var religion = jsonResponse.member.religion;
                                var maritalstatus = jsonResponse.member.maritalstatus;
                                var category = jsonResponse.member.category;
                                var landline = jsonResponse.member.landline;
                                var mobile_line = jsonResponse.member.mobile_line;
                                var delivery_address1 = jsonResponse.member.delivery_address1;
                                var delivery_address2 = jsonResponse.member.delivery_address2;
                                var corporate_address1 = jsonResponse.member.corporate_address1;
                                var corporate_address2 = jsonResponse.member.corporate_address2;
                                var name_of_organization = jsonResponse.member.name_of_organization;
                                var unique_registration_number = jsonResponse.member.unique_registration_number;
                                var business_category = jsonResponse.member.business_category;
                                var membershiptype = jsonResponse.membershiptype;
                                var renewal_date = jsonResponse.date_of_renewal;
                                var member_city = jsonResponse.member_city;
                                var member_state = jsonResponse.member_state;
                                var member_country = jsonResponse.member_country;
                                var member_delivery_city = jsonResponse.member_delivery_city;
                                var member_delivery_state = jsonResponse.member_delivery_state;
                                var member_delivery_country = jsonResponse.member_delivery_country;
                                var member_corporate_city = jsonResponse.member_corporate_city;
                                var member_corporate_state = jsonResponse.member_corporate_state;
                                var member_corporate_country = jsonResponse.member_corporate_country;
                                var id = jsonResponse.member.id;
                                var city_id = jsonResponse.member.city_id;
                                var state_id=jsonResponse.member.state_id;
                                var country_id=jsonResponse.member.country_id;
                                var delivery_city_id = jsonResponse.member.delivery_city_id;
                                var delivery_state_id=jsonResponse.member.delivery_state_id;
                                var delivery_country_id = jsonResponse.member.delivery_country_id;
                                var corporate_city_id = jsonResponse.member.corporate_city_id;
                                var corporate_state_id = jsonResponse.member.corporate_state_id;
                                var corporate_country_id = jsonResponse.member.corporate_country_id;
                                var membership_status = jsonResponse.membership_status;
                                var member_picture = jsonResponse.member.picture;
                                var role = jsonResponse.member.role;
                                var status = jsonResponse.member.status;
                                var usertype =  jsonResponse.member.usertype;
                                var membership_type_id = jsonResponse.membership_type_id;
                                var name = jsonResponse.member.name;






        					}

                            console.log('the picture of this member is:',member_picture);

                            //get the handle to the image

                            var image = win.down('#memberPicture');

                            //get the image source

                            image.setSrc('../cobuy_images/icons'+ '/' + member_picture);



        					var values = {

                                username:username,
                                email:email,
                                membership_number:membership_number,
                                firstname:firstname,
                                middlename:middlename,
                                lastname:lastname,
                                gender:gender,
                                address1:address1,
                                address2:address2,
                                dateofbirth:dateofbirth,
                                religion:religion,
                                maritalstatus:maritalstatus,
                                category:category,
                                landline:landline,
                                mobile_line:mobile_line,
                                delivery_address1:delivery_address1,
                                delivery_address2:delivery_address2,
                                corporate_address1:corporate_address1,
                                corporate_address2:corporate_address2,
                                name_of_organization:name_of_organization,
                                unique_registration_number:unique_registration_number,
                                business_category:business_category,
                                membership_type:membershiptype,
                                renewal_due_date:renewal_date,
                                city:member_city,
                                state:member_state,
                                country:member_country,
                                delivery_city:member_delivery_city,
                                delivery_state:member_delivery_state,
                                delivery_country:member_delivery_country,
                                corporate_city:member_corporate_city,
                                corporate_state:member_corporate_state,
                                corporate_country:member_corporate_country,
                                id:id,
                                city_id:city_id,
                                state_id:state_id,
                                country_id:country_id,
                                delivery_city_id:delivery_city_id,
                                delivery_state_id:delivery_state_id,
                                delivery_country_id:delivery_country_id,
                                corporate_city_id:corporate_city_id,
                                corporate_state_id:corporate_state_id,
                                corporate_country_id:corporate_country_id,
                                membership_status:membership_status,
                                role:role,
                                status:status,
                                usertype:usertype,
                                membership_type_id:membership_type_id,
                                user_id_of_member:id,
                                name:name

        					};


        					form.getForm().setValues(values);


        				}




        			});

        win.show();
    },

    onSignInButtonClick: function(button, e, eOpts) {
            //first confirm if the user is logged in
        Ext.Ajax.request({
           url: '/cobuy/index.php?r=Members/confirmIfUserIsLoggedIn',
                       success: function(response){
        				var jsonResponse = Ext.decode(response.responseText);
                          if(jsonResponse.success){
                              var userid = jsonResponse.userid;

                              if(userid === null || userid === undefined){
                                  //display the log in window

                                var win = Ext.create('Cobuy.view.Login');

                                //win.showAt(0,300);

                                  win.show();

                              }

                              console.log('the logged in user id is:', userid);

                          }
                   }

            });
    },

    onCartButtonClick: function(button, e, eOpts) {
        var win = Ext.create('Cobuy.view.ItemsInACartWin');

        var form = win.down('form');

        Ext.Ajax.request({

        				 url: '/cobuy/index.php?r=Members/retrieveMemberCartDetails',
        			     //success or failure
        				success: function(response){
        				var jsonResponse = Ext.decode(response.responseText);
        					if (jsonResponse.success) {

                                var username = jsonResponse.member.username;
                                var email = jsonResponse.member.email;
                                var membership_number = jsonResponse.member.membership_number;
                                var firstname = jsonResponse.member.firstname;
                                var middlename = jsonResponse.member.middlename;
                                var lastname = jsonResponse.member.lastname;
                                var gender = jsonResponse.member.gender;
                                var address1 = jsonResponse.member.address1;
                                var address2 = jsonResponse.member.address2;
                                var dateofbirth = jsonResponse.member.dateofbirth;
                                var religion = jsonResponse.member.religion;
                                var maritalstatus = jsonResponse.member.maritalstatus;
                                var category = jsonResponse.member.category;
                                var landline = jsonResponse.member.landline;
                                var mobile_line = jsonResponse.member.mobile_line;
                                var delivery_address1 = jsonResponse.member.delivery_address1;
                                var delivery_address2 = jsonResponse.member.delivery_address2;
                                var corporate_address1 = jsonResponse.member.corporate_address1;
                                var corporate_address2 = jsonResponse.member.corporate_address2;
                                var name_of_organization = jsonResponse.member.name_of_organization;
                                var unique_registration_number = jsonResponse.member.unique_registration_number;
                                var business_category = jsonResponse.member.business_category;
                                var membershiptype = jsonResponse.membershiptype;
                                var renewal_date = jsonResponse.date_of_renewal;
                                var member_city = jsonResponse.member_city;
                                var member_state = jsonResponse.member_state;
                                var member_country = jsonResponse.member_country;
                                var member_delivery_city = jsonResponse.member_delivery_city;
                                var member_delivery_state = jsonResponse.member_delivery_state;
                                var member_delivery_country = jsonResponse.member_delivery_country;
                                var member_corporate_city = jsonResponse.member_corporate_city;
                                var member_corporate_state = jsonResponse.member_corporate_state;
                                var member_corporate_country = jsonResponse.member_corporate_country;
                                var id = jsonResponse.member.id;
                                var city_id = jsonResponse.member.city_id;
                                var state_id=jsonResponse.member.state_id;
                                var country_id=jsonResponse.member.country_id;
                                var delivery_city_id = jsonResponse.member.delivery_city_id;
                                var delivery_state_id=jsonResponse.member.delivery_state_id;
                                var delivery_country_id = jsonResponse.member.delivery_country_id;
                                var corporate_city_id = jsonResponse.member.corporate_city_id;
                                var corporate_state_id = jsonResponse.member.corporate_state_id;
                                var corporate_country_id = jsonResponse.member.corporate_country_id;
                                var membership_status = jsonResponse.membership_status;
                                var member_picture = jsonResponse.member.picture;
                                var role = jsonResponse.member.role;
                                var status = jsonResponse.member.status;
                                var usertype =  jsonResponse.member.usertype;
                                var membership_type_id = jsonResponse.membership_type_id;
                                var order_id=jsonResponse.order;
                                var cart_gross_amount= jsonResponse.cart_gross_amount;
                                var cart_discount_amount = jsonResponse.cart_discount_amount;
                                var cart_net_amount = jsonResponse.cart_net_amount;
                                var payable_ondelivery_product_cost = jsonResponse.payable_ondelivery_product_cost;
                                var payable_before_delivery_product_cost = jsonResponse.payable_before_delivery_product_cost;
                                var total_amount = parseFloat(cart_gross_amount);
                                 var ondelivery_delivery_charges = 0;
                                var ondelivery_total_amount = payable_ondelivery_product_cost + ondelivery_delivery_charges;
                                var non_ondelivery_delivery_charges = 0;
                                var total_ondelivery_total_amount = parseFloat(ondelivery_total_amount);

                                var escrow_charges = jsonResponse.escrow_charges;
                               var non_ondelivery_total_amount = payable_before_delivery_product_cost + non_ondelivery_delivery_charges;
                                var total_non_ondelivery_total_amount = parseFloat(non_ondelivery_total_amount);


                                console.log('the total_amount issss:',total_amount);



        					}

                            console.log('payable_before_delivery_product_cost:',payable_before_delivery_product_cost);

                            console.log('total_non_ondelivery_total_amount:',total_non_ondelivery_total_amount);

                            console.log('total_ondelivery_total_amount:',total_ondelivery_total_amount);

                            console.log('payable_ondelivery_product_cost:',payable_ondelivery_product_cost);


                         /**   console.log('the picture of this member is:',member_picture);

                            //get the handle to the image

                            var image = win.down('#memberPicture');

                            //get the image source

                            image.setSrc('../cobuy_images/icons' + '/' + member_picture);
                            **/


        					var values = {

                                username:username,
                                email:email,
                                membership_number:membership_number,
                                firstname:firstname,
                                middlename:middlename,
                                lastname:lastname,
                                gender:gender,
                                address1:address1,
                                address2:address2,
                                dateofbirth:dateofbirth,
                                religion:religion,
                                maritalstatus:maritalstatus,
                                category:category,
                                landline:landline,
                                mobile_line:mobile_line,
                                delivery_address1:delivery_address1,
                                delivery_address2:delivery_address2,
                                corporate_address1:corporate_address1,
                                corporate_address2:corporate_address2,
                                name_of_organization:name_of_organization,
                                unique_registration_number:unique_registration_number,
                                business_category:business_category,
                                membership_type:membershiptype,
                                renewal_due_date:renewal_date,
                                city:member_city,
                                state:member_state,
                                country:member_country,
                                delivery_city:member_delivery_city,
                                delivery_state:member_delivery_state,
                                delivery_country:member_delivery_country,
                                corporate_city:member_corporate_city,
                                corporate_state:member_corporate_state,
                                corporate_country:member_corporate_country,
                                id:id,
                                city_id:city_id,
                                state_id:state_id,
                                country_id:country_id,
                                delivery_city_id:delivery_city_id,
                                delivery_state_id:delivery_state_id,
                                delivery_country_id:delivery_country_id,
                                corporate_city_id:corporate_city_id,
                                corporate_state_id:corporate_state_id,
                                corporate_country_id:corporate_country_id,
                                membership_status:membership_status,
                                role:role,
                                status:status,
                                usertype:usertype,
                                membership_type_id:membership_type_id,
                                order_id:order_id,
                                cart_gross_amount:Ext.util.Format.number(cart_gross_amount,'0,000.00'),
                                //cart_gross_amount:cart_gross_amount,
                                cart_amount_for_computation:cart_gross_amount,
                                cart_discount_amount:cart_discount_amount,
                                cart_net_amount:cart_net_amount,
                                total_amount:Ext.util.Format.number(total_amount,'0,000.00'),
                                ondelivery_cost_of_items:Ext.util.Format.number(payable_ondelivery_product_cost,'0,000.00'),
                                ondelivery_delivery_charges:Ext.util.Format.number(ondelivery_delivery_charges,'0,000.00'),
                                ondelivery_total_amount:Ext.util.Format.number(total_ondelivery_total_amount,'0,000.00'),
                                non_ondelivery_cost_of_items:Ext.util.Format.number(payable_before_delivery_product_cost,'0,000.00'),
                                non_ondelivery_delivery_charges:Ext.util.Format.number(non_ondelivery_delivery_charges,'0,000.00'),
                                non_ondelivery_total_amount:Ext.util.Format.number(non_ondelivery_total_amount,'0,000.00'),
                                ondelivery_cost_of_items_for_computation:payable_ondelivery_product_cost,
                                ondelivery_delivery_charges_for_computation:ondelivery_delivery_charges,
                                ondelivery_total_amount_for_computation:total_ondelivery_total_amount,
                                non_ondelivery_cost_of_items_for_computation:payable_before_delivery_product_cost,
                                non_ondelivery_delivery_charges_for_computation:non_ondelivery_delivery_charges,
                                non_ondelivery_total_amount_for_computation:total_non_ondelivery_total_amount,
                                non_ondelivery_escrow_charges:Ext.util.Format.number(escrow_charges,'0,000.00'),
                                non_ondelivery_escrow_charges_for_computation:escrow_charges




        					};


        					form.getForm().setValues(values);


        				}




        			});

        win.show();
    },

    onJoinButtonClick: function(button, e, eOpts) {
        var win = Ext.create('Cobuy.view.NewMembershipSubscriptionWin');

        win.show();
    },

    onCloseButtonClick: function(button, e, eOpts) {
        var win = button.up('window');

        win.destroy();
    },

    onCancelButtonClick1: function(button, e, eOpts) {
        var win = button.up('window');

        win.destroy();
    },

    onLoginButtonClick: function(button, e, eOpts) {
        console.log('login button clicked');
    },

    onTermCheckboxfieldChange: function(field, newValue, oldValue, eOpts) {
        var win = field.up('window');

        if(newValue == 1){
            //activate the term button
            win.down('#termsBtn').setDisabled(false);
            win.down('#paymentBtn').setDisabled(false);
             win.down('#submitBtn').setDisabled(false);

        }else{
            win.down('#termsBtn').setDisabled(true);
            win.down('#paymentBtn').setDisabled(true);
            win.down('#submitBtn').setDisabled(true);

        }
    },

    onMainviewportViewportRender: function(component, eOpts) {
        Ext.Ajax.request({

        				 url: '/cobuy/index.php?r=Service/retrieveNecessaryInformation',
        			     //success or failure
        				success: function(response){
        				var jsonResponse = Ext.decode(response.responseText);
        					if (jsonResponse.success) {

                                var general_icon = jsonResponse.general_icon;
                                var share_icon = jsonResponse.share_icon;
                                var business_icon = jsonResponse.business_icon;




        					}

                            console.log('the picture of this member is:',general_icon);

                            //get the handle to the image

                            var general_image = component.down('#generalserviceImg');
                            var share_image = component.down('#shateserviceImg');
                            var business_image = component.down('#businessserviceImg');

                            //get the image source

                            general_image.setSrc('../cobuy_images/icons' + '/' + general_icon);

                             share_image.setSrc('../cobuy_images/icons' + '/' + share_icon);

                            business_image.setSrc('../cobuy_images/icons' + '/' + business_icon);






        				}




        			});


        //load both the category and the product type combos

        component.down('#serviceCombo').getStore().load();



        component.down('#productCategoryCombo').getStore().load({
            params:{
                service_id:0,
                category_id:0
            }
        });


        component.down('#productTypeCombo').getStore().load({
            params:{
                category_id:0,
                service_id:0
            }
        });



    },

    onMainviewportViewportAfterRender: function(component, eOpts) {
        //first confirm if the user is logged in
        Ext.Ajax.request({
           url: '/cobuy/index.php?r=Members/confirmIfUserIsLoggedIn',
                       success: function(response){
        				var jsonResponse = Ext.decode(response.responseText);
                          if(jsonResponse.success){
                              var userid = jsonResponse.userid;
                              var firstname = jsonResponse.firstname;
                              var length = jsonResponse.length;
                              var email = jsonResponse.member_email;
                              var membership_number = jsonResponse.membership_number;
                              var with_open_order = jsonResponse.with_open_order;

                              console.log('the member id is:',userid);
                              console.log('the member email is:',email);
                              console.log('the member member number is:',membership_number);
                              console.log('is there any open order:',with_open_order);
                          }
                           if(userid != null || userid != undefined){
                                  //display the log in window
                                //increase the size of the button
                               // var button_size = component.down('#logoutBtn').getWidth();
                              //  component.down('#logoutBtn').setWidth(button_size +length );
                               // component.down('#logoutBtn').setText('Logout'+ ' '+ '<font color="yellow">'+firstname + '!' +'</font>');
                                component.down('#logoutBtn').setIconCls('logoff');
                                 component.down('#logoutBtn').setVisible(true);
                               component.down('#accountsBtn').setDisabled(false);
                              component.down('#cartBtn').setDisabled(false);
                               component.down('#signinBtn').setVisible(false);
                               component.down('#joinBtn').setVisible(false);
                               component.down('#joinSeparator').setVisible(false);


                               //make it login button invisible
                             // component.down('#signinBtn').setVisible(false);
                               var values = {
                                   userid: userid
                               };
                                Ext.getCmp('mainviewport').down('#userid').getForm().setValues(values);
                               var payment_values = {
                                   email:email,
                                   membership_number:membership_number
                               };
                                Ext.getCmp('mainviewport').down('#collectible').getForm().setValues(payment_values);

                           }else{
                              component.down('#signinBtn').setVisible(true);

                           }
                   }





        });


        //load the central panel combos

        //load both the category and the product type combos




        component.down('#productCategoryCombo').getStore().load({
            params:{
                service_id:0,
                category_id:0
            }
        });


        component.down('#productTypeCombo').getStore().load({
            params:{
                category_id:0,
                type_id:0
            }
        });
    },

    ovAddComponentClickEvent: function(component, eOpts) {
        component.getEl().on('click', function() {



              component.fireEvent('click', component);



            });


    },

    init: function(application) {
        this.control({
            "mainviewport button#aboutusBtn": {
                click: this.onAboutUsButtonClick
            },
            "mainviewport button#servicesBtn": {
                click: this.onServicesButtonClick
            },
            "mainviewport button#membershipBtn": {
                click: this.onMembershipButtonClick
            },
            "mainviewport button#contactusBtn": {
                click: this.onContactUsButtonClick
            },
            "mainviewport button#accountsBtn": {
                click: this.onAccountsButtonClick
            },
            "mainviewport button#signinBtn": {
                click: this.onSignInButtonClick
            },
            "mainviewport button#cartBtn": {
                click: this.onCartButtonClick
            },
            "mainviewport button#joinBtn": {
                click: this.onJoinButtonClick
            },
            "button#closeBtn": {
                click: this.onCloseButtonClick
            },
            "button#cancelBtn": {
                click: this.onCancelButtonClick1
            },
            "login button#loginBtn": {
                click: this.onLoginButtonClick
            },
            "checkboxfield#termCheckbox": {
                change: this.onTermCheckboxfieldChange
            },
            "mainviewport": {
                render: this.onMainviewportViewportRender,
                afterrender: this.onMainviewportViewportAfterRender
            },
            "[cls~=ovAddComponentClickEvent]": {
                afterrender: this.ovAddComponentClickEvent
            }
        });
    }

});
