/*
 * File: app/controller/ProductImagesViewController.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Cobuy.controller.ProductImagesViewController', {
    extend: 'Ext.app.Controller',

    onProductImagesViewWindowRender: function(component, eOpts) {
        var product_id = component.down('form').down('hiddenfield[name=product_id]').getValue();

        Ext.Ajax.request({

        				 url: '/cobuy/index.php?r=Product/retrieveProductDetails',
                        params:{
                            product_id:product_id
                        },
        			     //success or failure
        				success: function(response){
        				var jsonResponse = Ext.decode(response.responseText);
        					if (jsonResponse.success) {

                                var mainview = jsonResponse.product.icon;
                                var frontview = jsonResponse.product.product_front_view;
                                var backview = jsonResponse.product.product_back_view;
                                var rightsideview = jsonResponse.product.product_right_side_view;
                                var leftsideview = jsonResponse.product.product_left_side_view;
                                var topview = jsonResponse.product.product_top_view;
                                var bottomview = jsonResponse.product.product_bottom_view;
                                var contentview = jsonResponse.product.product_contents_or_booth_view;
                                var insidefrontview = jsonResponse.product.product_inside_view;
                                var insidedashboardview = jsonResponse.product.product_dashboard_view;
                                var engineview = jsonResponse.product.product_engine_view;





        					}

                            //get the handle to the image

                           // var mainview_image = component.down('#mainviewImg');
                            var frontview_image = component.down('#frontviewImg');
                            var backview_image = component.down('#backviewImg');
                            var rightsideview_image = component.down('#rightsideviewImg');
                            var leftsideview_image = component.down('#leftsideviewImg');
                            var topview_image = component.down('#topviewImg');
                            var bottomview_image = component.down('#bottomviewImg');
                            var contentview_image = component.down('#contentviewImg');
                            var insideview_image = component.down('#insidefrontviewImg');
                            var insidedashboardview_image = component.down('#insidedashboardImg');
                            var engineview_image = component.down('#engineviewImg');


                            //get the image source
                             //set the height of this image
                           // mainview_image.setHeight(231);
                            //mainview_image.setWidth(128);

                           // mainview_image.setSrc('../admin.oneroof.com.ng/cobuy_images/icons' + '/' + mainview);


                            //set the title of the fieldser
                            //component.down('#mainFieldset').setTitle('Some Cool Complete Image');

                             frontview_image.setSrc('../admin.oneroof.com.ng/cobuy_images/icons' + '/' + frontview);
                            //component.down('#frontFieldset').setTitle('Some Cool Complete Front Image');

                            backview_image.setSrc('../admin.oneroof.com.ng/cobuy_images/icons' + '/' + backview);

                            rightsideview_image.setSrc('../admin.oneroof.com.ng/cobuy_images/icons' + '/' + rightsideview);

                            leftsideview_image.setSrc('../admin.oneroof.com.ng/cobuy_images/icons' + '/' + leftsideview);

                            topview_image.setSrc('../admin.oneroof.com.ng/cobuy_images/icons' + '/' + topview);

                            bottomview_image.setSrc('../admin.oneroof.com.ng/cobuy_images/icons' + '/' + bottomview);

                            contentview_image.setSrc('../admin.oneroof.com.ng/cobuy_images/icons' + '/' + contentview);

                           insideview_image.setSrc('../admin.oneroof.com.ng/cobuy_images/icons' + '/' + insidefrontview);

                          insidedashboardview_image.setSrc('../admin.oneroof.com.ng/cobuy_images/icons' + '/' + insidedashboardview);

                          engineview_image.setSrc('../admin.oneroof.com.ng/cobuy_images/icons' + '/' + engineview);







        				}




        			});
    },

    onViewingConstituentImageWindowRender: function(component, eOpts) {
        var product_id = component.down('form').down('hiddenfield[name=id]').getValue();

        //var order_id = component.down('form').down('hiddenfield[name=order]').getValue();


        Ext.Ajax.request({

        				 url: '/cobuy/index.php?r=ProductConstituents/retrieveProductConstituentDetails',
                        params:{
                            id:product_id
                            //order_id:order_id
                        },
        			     //success or failure
        				success: function(response){
        				var jsonResponse = Ext.decode(response.responseText);
        					if (jsonResponse.success) {

                                var mainview = jsonResponse.product.icon;
                                var frontview = jsonResponse.product.product_front_view;
                                var backview = jsonResponse.product.product_back_view;
                                var rightsideview = jsonResponse.product.product_right_side_view;
                                var leftsideview = jsonResponse.product.product_left_side_view;
                                var topview = jsonResponse.product.product_top_view;
                                var bottomview = jsonResponse.product.product_bottom_view;
                                var contentview = jsonResponse.product.product_contents_or_booth_view;
                                var insidefrontview = jsonResponse.product.product_inside_view;
                                var insidedashboardview = jsonResponse.product.product_dashboard_view;
                                var engineview = jsonResponse.product.product_engine_view;





        					}

                            //get the handle to the image

                            //var mainview_image = component.down('#mainviewImg');
                            var frontview_image = component.down('#frontviewImg');
                            var backview_image = component.down('#backviewImg');
                            var rightsideview_image = component.down('#rightsideviewImg');
                            var leftsideview_image = component.down('#leftsideviewImg');
                            var topview_image = component.down('#topviewImg');
                            var bottomview_image = component.down('#bottomviewImg');
                            var contentview_image = component.down('#contentviewImg');
                            var insideview_image = component.down('#insidefrontviewImg');
                            var insidedashboardview_image = component.down('#insidedashboardImg');
                            var engineview_image = component.down('#engineviewImg');


                            //get the image source

                           // mainview_image.setSrc('../admin.oneroof.com.ng/cobuy_images/icons' + '/' + mainview);

                            //set the title of the fieldser
                            //component.down('#mainFieldset').setTitle('Some Cool Complete Image');

                             frontview_image.setSrc('../admin.oneroof.com.ng/cobuy_images/icons' + '/' + frontview);
                            //component.down('#frontFieldset').setTitle('Some Cool Complete Front Image');

                            backview_image.setSrc('../admin.oneroof.com.ng/cobuy_images/icons' + '/' + backview);

                            rightsideview_image.setSrc('../admin.oneroof.com.ng/cobuy_images/icons' + '/' + rightsideview);

                            leftsideview_image.setSrc('../admin.oneroof.com.ng/cobuy_images/icons' + '/' + leftsideview);

                            topview_image.setSrc('../admin.oneroof.com.ng/cobuy_images/icons' + '/' + topview);

                            bottomview_image.setSrc('../admin.oneroof.com.ng/cobuy_images/icons' + '/' + bottomview);

                            contentview_image.setSrc('../admin.oneroof.com.ng/cobuy_images/icons' + '/' + contentview);

                           insideview_image.setSrc('../admin.oneroof.com.ng/cobuy_images/icons' + '/' + insidefrontview);

                          insidedashboardview_image.setSrc('../cobuy_images/icons' + '/' + insidedashboardview);

                          engineview_image.setSrc('../admin.oneroof.com.ng/cobuy_images/icons' + '/' + engineview);







        				}




        			});
    },

    init: function(application) {
        this.control({
            "productimagesviewwin": {
                render: this.onProductImagesViewWindowRender
            },
            "constituentsviewimageswin": {
                render: this.onViewingConstituentImageWindowRender
            }
        });
    }

});
